version: '3'

services:

  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      MONGODB_DATABASE: sales-db
      MONGODB_USER: admin
      MONGODB_PASS: mongodb

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672